services:
  postgres:
    image: supabase/postgres:14.1.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - ./scripts/seed:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  gotrue:
    image: supabase/gotrue:v2.5.5
    restart: always
    environment:
      - API_EXTERNAL_URL=http://localhost:9999
      - GOTRUE_SITE_URL=http://localhost:3000
      - GOTRUE_JWT_SECRET=${JWT_SECRET}
      - GOTRUE_DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    ports:
      - '9999:9999'
    depends_on:
      postgres:
        condition: service_healthy

  realtime:
    image: supabase/realtime:v0.15.0
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_SSL=false
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - '4000:4000'
    depends_on:
      postgres:
        condition: service_healthy

  storage:
    image: supabase/storage-api:v0.12.0
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      - JWT_SECRET=${JWT_SECRET}
      - ANON_KEY=${ANON_KEY}
      - SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
      - FILE_SIZE_LIMIT=52428800
      - TENANT_ID=stub
    ports:
      - '5000:5000'
    depends_on:
      postgres:
        condition: service_healthy

  studio:
    image: supabase/studio:latest
    restart: always
    environment:
      - SUPABASE_URL=http://localhost:8000
      - SUPABASE_ANON_KEY=${ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
    ports:
      - '54323:3000'
    depends_on:
      - gotrue
      - realtime
      - storage
